CUDA_VISIBLE_DEVICES=7 python ./baichuan2_dpo.py \
    --model_name_or_path /data2/home/yangbt/projects/llm-chat-finetune/merge_models/baichuan2-zhuiwen-multiple-v4 \
    --experiment_name baichuan2-dpo-test \
    --run_name debug \
    --train_file_dir /data2/home/yangbt/dataset/rlhf/zhihu_rlhf_3k/train.csv \
    --valid_file_dir /data2/home/yangbt/dataset/rlhf/zhihu_rlhf_3k/test.csv \
    --output_dir /data2/home/yangbt/projects/llm-rlhf/dpo/zhuiwen/debug \
    --num_train_epochs 2 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --warmup_steps 100 \
    --weight_decay 0.05 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_r 8 \
    --target_modules W_pack \
    --load_in_4bit True \
    --load_in_8bit False \
    --max_prompt_length 2048 \
    --max_length 4096 \
    --logging_steps 10 \
    --save_steps 10 \
    --eval_steps 10 \
    --save_total_limit 5 \
    --sanity_check False
